### ISSUE TITLE
Please fix the slow transition between zoom's

### ISSUE THREAD

**Issue by vlipcean** [roataway/web-ui#77] opened 2019-11-03 07:13 UTC
Please fix the slow transition between the zoom in and zoom out by changing this class .markerImg { transition: all 0s; };

**Comment by roata** [comment] 2019-11-03 09:46
Can you make a pull request with this change?

This way we'll get an automated test build, to see what the result looks like before accepting the change into master.

We actually need the slow transition, but only when the map is NOT being zoomed. The pull request should address that, and keep it off only when a zoom operation is performed.

**Comment by roata** [comment] 2020-05-30 16:00
@vlipcean, there is a reason the transition is there - the telemetry arrives every ~10s, so the transition allows a smooth change of the marker from one place to another.

What we need is to remove the transition while we're zooming, but restore it after the zoom is complete. Can you make this change?

**Comment by roata** [comment] 2020-05-30 16:17
Duplicate of #49

**Closed by roata** 2020-05-30 16:17 UTC
